version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - seatsavvy
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 5500:5500
    networks:
      - seatsavvy

  db:
    container_name: seatsavvy_db
    image: postgres:17
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - seatsavvy
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=seatsavvy

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  seatsavvy:
    external: true
