services:
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./apps/web:/app/apps/web
  #     - /app/apps/web/node_modules
  #   networks:
  #     - seatsavvy
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - 5500:5500
  #   volumes:
  #     - ./apps/api:/app/apps/api
  #     - /app/apps/api/node_modules
  #   networks:
  #     - seatsavvy

  db:
    container_name: seatsavvy_db
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - seatsavvy
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=seatsavvy

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  seatsavvy:
