// NOTE: If updating values update in both
export enum Genre {
  Action = "Action",
  Adventure = "Adventure",
  Comedy = "Comedy",
  Crime = "Crime",
  Drama = "Drama",
  Fantasy = "Fantasy",
  Historical = "Historical",
  Horror = "Horror",
  Mystery = "Mystery",
  Romance = "Romance",
  ScienceFiction = "Science Fiction",
  Thriller = "Thriller",
  Western = "Western",
  Animation = "Animation",
  Documentary = "Documentary",
  Family = "Family",
  Musical = "Musical",
  War = "War",
  Biography = "Biography",
  Sport = "Sport",
}

export const genres = [
  "Action",
  "Adventure",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Historical",
  "Horror",
  "Mystery",
  "Romance",
  "Science Fiction",
  "Thriller",
  "Western",
  "Animation",
  "Documentary",
  "Family",
  "Musical",
  "War",
  "Biography",
  "Sport",
] as const;
